# Generated by Django 4.0.1 on 2022-04-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Title', models.CharField(max_length=50)),
                ('Expertise', models.CharField(max_length=50)),
                ('Education', models.CharField(max_length=50)),
            ],
        ),
    ]
